package com.ustadmobile.door.sqljsjdbc

import com.ustadmobile.door.jdbc.*
import kotlin.Array

class SQLiteConnectionJs(val datasource: SQLiteDatasourceJs):Connection {

    private var closed = false

    private var mAutoCommit = true

    override fun setAutoCommit(commit: Boolean) {
        mAutoCommit = commit
    }

    override fun getAutoCommit(): Boolean {
        return mAutoCommit
    }

    override fun prepareStatement(sql: String): PreparedStatement {
        return SQLitePreparedStatementJs(this, sql)
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        return SQLitePreparedStatementJs(this, sql, autoGeneratedKeys)
    }

    override fun createStatement(): Statement {
        return SQLiteStatementJs(this)
    }

    override fun commit() {}

    override fun close() {
        closed = true
    }

    override fun isClosed() = closed

    override fun createArrayOf(arrayType: String, objects: Array<out Any?>): com.ustadmobile.door.jdbc.Array {
        throw SQLException("Array not supported on SQLite")
    }

    override fun getMetaData(): DatabaseMetadata {
        return SQLiteDatabaseMetadataJs(datasource)
    }


}