package com.ustadmobile.door.ext

import com.ustadmobile.door.DoorDatabase
import com.ustadmobile.door.replication.ReplicationEntityMetaData
import kotlin.reflect.KClass

/**
 * Metadata that is generated by the annotation processor for each door database. This provides useful properties
 * e.g. the TableIdMap, Database KClass, etc that can be used at runtime.
 *
 * The metadata can be retrieved via extension functions dbInstance.doorDatabaseMetadata() or dbClass.doorDatabaseMetadata()
 */
abstract class DoorDatabaseMetadata<T: DoorDatabase> {

    /**
     * Map of Table Name -> TableId for all syncable tables.
     */
    abstract val syncableTableIdMap: Map<String, Int>

    /**
     * The KClass object for this database.
     */
    abstract val dbClass: KClass<T>

    abstract val replicateEntities: Map<Int, ReplicationEntityMetaData>

    companion object {

        /**
         * The Suffix that is added to create the generated class. E.g. For ExampleDatabase the metadata class will be
         * ExampleDatabase_DoorMetadata
         */
        const val SUFFIX_DOOR_METADATA = "_DoorMetadata"

    }

}