package com.ustadmobile.door.jdbc

actual interface Connection {

    actual fun setAutoCommit(commit: Boolean)

    actual fun prepareStatement(sql: String): PreparedStatement

    actual fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement

    actual fun createStatement(): Statement

    actual fun commit()

    actual fun close()

    actual fun isClosed(): Boolean

    actual fun createArrayOf(
        arrayType: String,
        objects: kotlin.Array<out Any?>
    ): Array

    actual fun getMetaData(): DatabaseMetadata

    actual fun getAutoCommit(): Boolean

}