package com.ustadmobile.door.jdbc

/**
 * Represents a connection where some things need to be done asycnhronously. This is only used on Javascript at the moment.
 */
interface AsyncConnection : Connection {

    suspend fun setAutoCommitAsync(commit: Boolean)

    suspend fun commitAsync()

    suspend fun prepareStatementAsync(sql: String): PreparedStatement

    suspend fun prepareStatementAsync(sql: String, autoGeneratedKeys: Int): PreparedStatement
}